### ISSUE TITLE
How do I fix "unstable r on player"?

### ISSUE THREAD

**Issue by nolior** [pfmonville/whole_history_rating#1]
I'm running your library on a few years worth of data (starting in 2014 - now) in a relatively volatile sport. There are approximately 60,000 matches. I'm receiving the exception "unstable r on player". 

Does this mean that there's a bug in my code somewhere? Or perhaps the algorithm doesn't work as well on this particular sport?

**Comment by pfmonville** [comment]
I cannot investigate further right now, but I will next Monday.
I did a port of the ruby implementation, so any questions relative to the algorithm should be asked to the guys at goshrine https://github.com/goshrine/whole_history_rating 

The exception is raised in player.py in the function update_by_ndim_newton
The rating for a specific day for a specific player do not respect a condition. It requires further investigation to know if the test is not buggy and how to fix it. In the mean time if you absolutely need a result you can comment the lines 120,121,123 in player.py but there is no guarantee that the result will have all the properties of Bayesian algorithm.

**Comment by nolior** [comment]
Thanks for the response, just saw this. 
I ended up not being able to figure out how to resolve this. Still not 100% sure if it was my mistake or the libraries' issue. 

I will be closing this issue since I am no longer pursuing it.
