### ISSUE TITLE
Why the uncertainty attribute is multiplied by 100 in the ratings_for_player function?

### ISSUE THREAD

**Issue by joudinet** [pfmonville/whole_history_rating#4]
On this line:
https://github.com/pfmonville/whole_history_rating/blob/47d6724f983e6d7f800fa27d61f49bc247942ae0/whr/whole_history_rating.py#L114

The uncertainty attribute (which is the variance if I understood correctly the code) is multiplied by 100 for some unknown reason. The documentation of this function says it returns the uncertainty, so why does it multiply it by 100?

**Comment by pfmonville** [comment]
It’s a good question,
I checked the paper of Remi Coulom and there is not the presence of a factor 100.
Those lines of code are a perfect copy of the ruby implementation on which I based this version. The uncertainty is used only to be updated and in the print_ordered_rating function which only serve to print player’s rating.
Why it is displayed with a factor 100 I honestly don’t know.


The only two instances where uncertainty appears in the ruby code:
in base.rb
```ruby
def ratings_for_player(name)
  ...
  player.days.map {|d| [d.day, d.elo.round, (d.uncertainty*100).round]}
end
```
In player.rb
```ruby
def update_uncertainty
  ...
  days.zip(u) {|d,u| d.uncertainty = u}
end
```

**Comment by joudinet** [comment]
Hum, then that's a mystery and it looks like the original ruby code is not maintained anymore (no more commit since 2012). I've quickly checked the forked projects but they do not seem to have changed this function neither.

I want to print a 95% interval confidence based of this value and I'm not sure how I should interpret it with this 100 factor.
Currently, I simply ignore it and suppose it is the variance. So, I print elo ± 1.96 times the square root of this value.
The results look good to me but I'm not an expert and would like to be sure. Anyway, thanks for your reply and hope someone will find an explanation. Best,

**Comment by endolith** [comment]
@joudinet Have you figured out the proper way?

**Comment by endolith** [comment]
See https://github.com/goshrine/whole_history_rating/issues/1#issuecomment-1935317549 for ChatGPT's opinion about the multiplication by 100:

> No, it's not standard practice to multiply variance by 100 to convert it to a percentage. Variance is a measure of the dispersion or spread in a set of values, and inherently, its dimensions are the square of the dimensions of the original data. Therefore, multiplying variance by 100 does not convert it into a percentage in the conventional sense.
> 
> There may be specific contexts or purposes where such scaling is carried out, but it wouldn't yield a unit or metric that has an established name or generally accepted understanding.

Also, the rounding means that small values get squished to 0, which seems wrong.  I think it should return a float without any rounding or multiplication by 100, and say in the docstring that it's the variance of the rating.

**Comment by pfmonville** [comment]
Since it is multiplied by 100 only when it is displayed. For me it means that at goshrine they wanted to make a "pretty print".
They integrated it directly in the code and not in their front end.

As it seems to have no specific effect and can easily be retrieved (just by multiplying the value by 100) I can remove the multiplication from the print ratings.

It is a divergence from the goshrine implementation, and all printed results will not be the same.

But it will not mess with Rémi Coulom's algorithm.

**Comment by pfmonville** [comment]
I remove the multiplication by 100 and rounded by two digits, now it is displayed 0.84 instead of 84 (just as an exemple).
I'll close this issue

**Comment by joudinet** [comment]
Few years later, I think I finally understand why the uncertainty attribute was multiplied by a constant in the ratings_for_player function. The ratings in this function are displayed in elo, thus the gamma value  * 400 / ln(10)).
I guess the author wanted to display the uncertainty here in something that could be added/subtracted from the elo rating to get confidence intervals, but it did the mistake to use the variance instead of the standard deviation and 100 is a rough approximation of 400 / ln(10).
Now, I do the following: `elo_uncertainty = np.sqrt(variance) * 400 / np.log(10)`, where variance is the current displayed uncertainty, so 0.84 in your example.
