### ISSUE TITLE
auto_iterate issues

### ISSUE THREAD

**Issue by endolith** [pfmonville/whole_history_rating#7]
* `iterates iteratively ten by ten` is confusing language
* `time_limit (int, optional): the maximal time after ` should mention that the time limit is measured in seconds
* The way the loop is arranged, the minimum number of iterations is actually 20, not 10, and it can take longer than the time limit if the dataset is large

I'm not sure the best way to improve these

**Comment by pfmonville** [comment]
The first two points can be easily improved. Regarding the third point, it was not suggested that the minimum number of iterations was 10; however, your point about the time limit stands correct. I implemented the time limit in the quickest manner available at that time. 
The time is calculated after each iteration, but in my tests, it never took so long as to make the time limit irrelevant.

**Comment by endolith** [comment]
OK, in my application it always does 20 iterations minimum, which takes 50 seconds, even if I say `time_limit=2`, which is why I was checking how it works.

**Comment by pfmonville** [comment]
I'll investigate the issue. It might be more effective to decrease the timeout checks for each iteration rather than doing so after every 10 iterations (and initially every 20).

However, you might find it more efficient to apply iterations individually like this:
```py
whr.iterate(count=1)
```

**Comment by pfmonville** [comment]
I've improved the auto_iterate function to take into account batch_size and perform precision and timeout checks once each batch is completed.

I've also cleaned up the code a bit with missing docstrings and type hints and dusted off the readme.

It's uploaded to pypi : the new version is 1.6.0

**Comment by pfmonville** [comment]
I uploaded it two quickly, take the 1.6.1 (for timeout handling in auto_iterate)
