### ISSUE TITLE
virtual_games Key Error

### ISSUE THREAD

**Issue by IronVillage** [pfmonville/whole_history_rating#8]
Double checked the games are in the right format and when I try and load them in I get this error.

whr.load_games(whr_hist, separator=",")

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Input In [325], in <cell line: 1>()
----> 1 whr.load_games(whr_hist, separator=",")

File ~\anaconda3\lib\site-packages\whr\whole_history_rating.py:309, in Base.load_games(self, games, separator)
    307     black = black.lower()
    308     white = white.lower()
--> 309 self.create_game(black, white, winner, time_step, handicap, extras=extras)

File ~\anaconda3\lib\site-packages\whr\whole_history_rating.py:145, in Base.create_game(self, black, white, winner, time_step, handicap, extras)
    143     black = black.lower()
    144     white = white.lower()
--> 145 game = self._setup_game(black, white, winner, time_step, handicap, extras)
    146 return self._add_game(game)

File ~\anaconda3\lib\site-packages\whr\whole_history_rating.py:121, in Base._setup_game(self, black, white, winner, time_step, handicap, extras)
    119 if black == white:
    120     raise AttributeError("Invalid game (black player == white player)")
--> 121 white_player = self.player_by_name(white)
    122 black_player = self.player_by_name(black)
    123 game = Game(black_player, white_player, winner, time_step, handicap, extras)

File ~\anaconda3\lib\site-packages\whr\whole_history_rating.py:93, in Base.player_by_name(self, name)
     91     name = name.lower()
     92 if self.players.get(name, None) is None:
---> 93     self.players[name] = Player(name, self.config)
     94 return self.players[name]

File ~\anaconda3\lib\site-packages\whr\player.py:13, in Player.__init__(self, name, config)
     10 self.debug = config.get('debug', False)
     11 self.w2 = (math.sqrt(config['w2']) * math.log(10.) /
     12            400.)**2.  # Convert from elo^2 to r^2
---> 13 self.virtual_games = config['virtual_games']
     14 self.days = []

KeyError: 'virtual_games'

**Comment by IronVillage** [comment]
I think some of my team names have commas in them, and it is messing with things. I added a virtual_games to the config and I think that's what it is.

**Comment by IronVillage** [comment]
ok sorted it, but unsure what value to assign "virtual_games", any ideas?

**Comment by pfmonville** [comment]
Hi,
what's strange is that "virtual_games" is nowhere to be found in the code, in any commit of the project. So, it's in your code that you add "virtual_games" to Base.config at some point.

However, you make me reconsider this part, and I notice that the save and load function I had made only takes "w2" in the config, which in any case forced the loss of additional information. I will correct this point so that all additional info is saved if possible, and display a warning otherwise.

**Comment by pfmonville** [comment]
I've just modified the behavior of save_base and load_base to capture everything in the config. This is implemented in release 1.6.2.

However, this is still unrelated to the KeyError for virtual_games in your code.

Oh, and regarding the commas in your team names, you can choose any separator you wish; it's unlikely they'll have '|' in their names.

**Comment by IronVillage** [comment]
Thank you
